### ISSUE TITLE
akka-projection-slick Scala 3 artifact/support/cross-build

### ISSUE THREAD

**Issue by chris-arrakis** [akka/akka-projection#1057]
### Short description

Slick itself is [now published](https://github.com/slick/slick/issues/2177#issuecomment-1628321681) for Scala 3, so I'm guessing it's possible to get this library there too now? I'm a little new to the Akka ecosystem, but from my attempts I couldn't find a way to use `akka-projection-slick` in Scala 3 due to conflicts from its dependencies.

### Details

I'm not sure if there's much to change in the library. Slick was of course blocking the upgrade because it uses macros, but now that it's been ported I don't see anything this this code that raises big flags (from my admittedly pretty Scala-2-inexperienced perspective). But I'm not sure if all the dependencies are also available for Scala 3 or can be pulled in from 2.13 in a non-conflicting way to a project based on e.g. `com.typesafe.akka:akka-actor-typed_3`.

From a brief look I'm guess this configuration will need to be updated: https://github.com/akka/akka-projection/blob/main/build.sbt#L59 to include `.settings(Scala3.settings)` to add the cross build.

Not sure what other steps are needed though!

**Comment by johanandren** [comment]
If you want to give it a shot a PR is welcome!

**Comment by patriknw** [comment]
Somewhat related to https://github.com/akka/akka-persistence-jdbc/pull/775

**Comment by PerWiklander** [comment]
This is now the last dependency blocking our team from adopting Scala 3 without a major rewrite of our projection code.

Slick is published for Scala 3.
akka-persistence-jdbc is published for Scala 3.

What needs to be done here and what can I help with?

**Comment by johanandren** [comment]
It has already been merged and the next akka-projection release will have all modules published for Scala 3

**Comment by PerWiklander** [comment]
Is there any plan for when "the next akka-projection release" might happen?

**Comment by johanandren** [comment]
In the coming two weeks

**Comment by johanandren** [comment]
FYI @PerWiklander this has now been released in akka-projection 1.5.4
