### ISSUE TITLE
Package samples as zips and publish with docs

### ISSUE THREAD

**Issue by johanandren** [akka/akka-projection#1058]
So that the distributed cluster and edge doc sites can refer to a zip-file instead of a place inside of a bigger repository that users must clone.

**Comment by patriknw** [comment]
I agree, for reference https://github.com/akka/akka-guide/blob/main/scripts/prepare-downloads.sh

**Comment by johanandren** [comment]
I think it would be enough to have them once per project and not keep historical zips around, so maybe a new directory on gustav and overwrite on release?

**Comment by patriknw** [comment]
Didn't see your comment until after PR. Quite nice to have them self contained within the docs though, hopefully not too large since it's just sources.

**Comment by johanandren** [comment]
Yeap, we can deal with disk filling up on server the day that really becomes a problem
