### ISSUE TITLE
Revisit database concurrency in KafkaToSlickIntegration example 

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#107]
The count can be updated by another Projection instance inbetween the read and the insertOrUpdate. See https://github.com/akka/akka-projection/pull/80/files#r421431861

> What I would use for CRUD, like this, is optimistic locking. A version number column that is read in findByEventType and then used as condition in the update to be the same as what was read. The update also increments it by 1. If no row was updated it means that someone else updated inbetween. Then we could fail, and even use the retry mechanism from #95
>
> Would be pretty nice to include that pattern in this example.
>
> An alternative would be to have one counter per projectionId, so that it's a single writer.

**Comment by seglo** [comment]
IMO this was resolved in #130. Instead of reading the count from the db it's incremented in the `UPDATE` statement itself.
