### ISSUE TITLE
Slow projection query

### ISSUE THREAD

**Issue by johanandren** [akka/akka-projection#1111]
Hi, we recently faced a problem with long DB queries and I think it's related to that issue. 

We have an app with small amount of entities (which results in small amount of slices) in the database. When projection makes a request for a range of slices where no entity exist yet, it uses `db_timestamp >= '1970-01-01 00:00:00+00'::timestamp with time zone` in a query and offset is not saved after that query. When other slice ranges becomes bigger in terms of saved events the query becomes longer because index is not used (I'm not sure why and details about that). Here is the report from Postgres for long query (8034.857 ms):

```
2024-01-09 13:34:58 UTC:10.0.6.239(40998):accounts_app1@accounts:[4133]:LOG:  duration: 8034.857 ms  plan:
	Query Text: SELECT slice, persistence_id, seq_nr, db_timestamp, CURRENT_TIMESTAMP AS read_db_timestamp, tags, event_ser_id, event_ser_manifest, event_payload, meta_ser_id, meta_ser_manifest, meta_payload FROM event_journal WHERE entity_type = $1 AND slice in (128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255) AND db_timestamp >= $2  AND db_timestamp < CURRENT_TIMESTAMP - interval '100 milliseconds' AND deleted = false ORDER BY db_timestamp, seq_nr LIMIT $3
	Limit  (cost=177909.06..178025.74 rows=1000 width=1008)
	  ->  Gather Merge  (cost=177909.06..193820.47 rows=136374 width=1008)
	        Workers Planned: 2
	        ->  Sort  (cost=176909.04..177079.51 rows=68187 width=1008)
	              Sort Key: db_timestamp, seq_nr
	              ->  Parallel Seq Scan on event_journal  (cost=0.32..173170.42 rows=68187 width=1008)
	                    Filter: ((NOT deleted) AND (db_timestamp >= '1970-01-01 00:00:00+00'::timestamp with time zone) AND ((entity_type)::text = 'TransactionCore'::text) AND (slice = ANY ('{128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255}'::integer[])) AND (db_timestamp < (CURRENT_TIMESTAMP - '00:00:00.1'::interval)))
```

For the query above no offset were saved and no entities exist in the slice range 128 to 255.

_Originally posted by @xeppaka in https://github.com/akka/akka-projection/issues/895#issuecomment-1884501209_

**Comment by patriknw** [comment]
I tried to reproduce this by having a few projection instances and only writing events to some of them. I can see a few different results from explain analyze depending on how many events I have populated the journal with and what db_timestamp > I use. However, it doesn't look wrong. For example, with 1 million events and query from 1970-01-01 of a slice range without any events it is using "Index Scan using event_journal_slice_idx".

@xeppaka Do you have any more input?

**Comment by xeppaka** [comment]
> event_journal_slice_idx

I'll make test again and bring more details.

**Comment by xeppaka** [comment]
This is the `event_journal` table I have during the testing (PostgreSQL 14.10):
[event_journal_202402021757.tar.gz](https://github.com/akka/akka-projection/files/14151057/event_journal_202402021757.tar.gz)

Note: there are no any `TransactionCore` entity events in slice 128-255.
Also note that I tested it on a bigger DB (more events saved) compared to the one in `event_journal_202402021757.tar.gz`.

This is the "slow" query taken from DB log:
```
explain(SELECT extract(EPOCH from db_timestamp)::BIGINT / 10 AS bucket, count(*) AS count FROM event_journal WHERE entity_type = 'TransactionCore'::text AND slice in (128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255) AND db_timestamp >= '1970-01-01 00:00:00+00'::timestamp with time zone AND db_timestamp <= '2024-02-02 20:00:00.000000+00'::timestamp with time zone AND deleted = false GROUP BY bucket ORDER BY bucket limit 10)
```

![image](https://github.com/akka/akka-projection/assets/1098039/e680127e-c99c-4fb3-a610-b98cdfab1f48)

When there are a lot of event saved for other slice (like slice 627 for `TransactionCore` from the event_journal_202402021757.tar.gz), then Parallel Seq Scan becomes slow.

If `db_timestamp >= '1970-01-01 00:00:00+00'` in the query is changed to `db_timestamp >= '2024-02-02 19:00:00+00'`, so query becomes this:
```
explain(SELECT extract(EPOCH from db_timestamp)::BIGINT / 10 AS bucket, count(*) AS count FROM event_journal WHERE entity_type = 'TransactionCore'::text AND slice in (128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255) AND db_timestamp >= '2024-02-02 19:00:00+00'::timestamp with time zone AND db_timestamp <= '2024-02-02 20:00:00.000000+00'::timestamp with time zone AND deleted = false GROUP BY bucket ORDER BY bucket limit 10)
```
then it uses index:

![image](https://github.com/akka/akka-projection/assets/1098039/ca873621-e68e-4b58-8960-39e1df3ad05d)

I'm not sure why after query is done, there is no offset saved and the next query again is using `db_timestamp >= '1970-01-01 00:00:00+00'`. Also if there are events saved in slice 128-255, it will probably work right.

I hope it will help to understand the problem.

**Comment by patriknw** [comment]
Thanks for more details. Normally the Postgres planner is supposed to know better than us, and this seems like an edge case to not have events for some slices. I can see a few workarounds:

1. Use more projection instances, i.e. smaller slice ranges. At least for your `event_journal_202402021757.tar.gz` it switches over to `Bitmap Index Scan on event_journal_slice_idx` when reducing the range to (128 ... 191).

2. Simulate events in all slice ranges periodically with some fake entities that just store events periodically. Doesn't to be often. You can randomly create persistenceId until you hit the right slice, using https://github.com/akka/akka/blob/899e984b0ac7e0ee4229749c80c6639771d920b6/akka-persistence/src/main/scala/akka/persistence/Persistence.scala#L461
You need one per slice range for each entity type, to move the offset forward.

3. If you are in control of the Postgres server you could set in `postgresql.conf`:
```
enable_seqscan = off
```

**Comment by xeppaka** [comment]
Thank you for the suggestions. I think it will be sufficient to resolve the problem.
