### ISSUE TITLE
Unexpected behavior when combine ShardedDaemonProcess with shared KafkaSourceProvider instance.

### ISSUE THREAD

**Issue by GreyPlane** [akka/akka-projection#1140]
Since the example code was initiate `KafkaSourceProvider` first and use it in Handler, one may expect that it's safe to share the instance over multiple handlers, eg: distribute projection via `ShardedDaemonProcess`.

But due to the mutable state `assignedPartitions` that inside `KafkaSourceProvider`, it will cause later started process to overwrite the previous process's `assignedPartitions`, causing `verifyOffset` always failed for some handlers.

I know this is probably not the intended usage, but would it better to provide some warns or change the example code to make people less likely making this kind of mistake?

**Comment by johanandren** [comment]
Sounds reasonable with a small warning around that example snippet in the docs.
