### ISSUE TITLE
runWithTestSink doesn't invoke handler.stop

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#134]
Would be good if the behavior was the same for both testkit run methods.

**Comment by renatocaval** [comment]
The reason is that the `runWithTestSink` doesn't stop the stream at all. 

We need to rethink this API. It should be something like:

```scala
projectionTestKit.runWithTestSink(projection) { sinkProbe =>
  sinkProbe.request(1)
  // do some assertions here
}
```

Then we can properly stop the projection when the user have finished their assertions.
