### ISSUE TITLE
Review ExecutionContext usage and support blocking handlers

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#148]
Might be using system.dispatcher in places where it should use something more specific from config or CassandraSessionProvider.

Also support blocking handlers, which might be related to JPA projections #23 that will probably be blocking.

**Comment by renatocaval** [comment]
See #361

**Comment by ignasi35** [comment]
#361 reviewed all Cassandra usages
#326 introduces start/stop for JDBC handlers

I think we should also add some examples/documentation so users implement their JDBC handlers isloating the JDBC blocking code on a separate execution context (the same used by the JDBC Offset store).

**Comment by renatocaval** [comment]
> I think we should also add some examples/documentation so users implement their JDBC handlers isloating the JDBC blocking code on a separate execution context (the same used by the JDBC Offset store).

This is already done. 

The JDBC handler is blocking by design. Users don't need to deal with Future/CompletionStage.
