### ISSUE TITLE
Too much ClassicActorSystemProvider?

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#149]
Did we go overboard with the usage of ClassicActorSystemProvider?

Projections will be run with ShardedDaemonProcess and ProjectionBehavior so there is already a dependency to Akka Typed.

Might be nice that it can be used with a system built with classic ActorSystem, but I don't see that as the primary target so it might be enough with using `.toTyped` for such integration.

At least we can use typed.ActorSystem in all places internally and only have ClassicActorSystemProvider in the user facing API.

**Comment by renatocaval** [comment]
I agree, I also had the impression we had too much of it. I find it particularly strange that we want to promote Akka Typed, but requires everywhere something called `ClassicActorSystemProvider`.
