### ISSUE TITLE
Shopping cart example

### ISSUE THREAD

**Issue by YikSanChan** [akka/akka-projection#169]
### Short description

Would be great to have a shopping cart example that makes it easy to understand what people can achieve with akka-projection provided they understand the shopping cart example with akka-persistence and akka-cluster-sharding

**Comment by patriknw** [comment]
Thanks for suggestion, I agree. We will update the existing shopping cart example to us Projections. https://github.com/akka/akka-samples/tree/2.6/akka-sample-cqrs-scala

**Comment by Tochemey** [comment]
I think a solution for this ticket https://github.com/lagom/lagom/issues/1346 will be very great.

**Comment by patriknw** [comment]
@Tochemey It is possible to run many (different) Akka Projections in the same service.

**Comment by patriknw** [comment]
@YikSanChan We have updated the shopping cart (cqrs) sample to use Akka Projections in https://github.com/akka/akka-samples/pull/214
The branch is https://github.com/akka/akka-samples/tree/wip-pojections-in-cqrs until we have merged the PR.

We will use this sample in a getting started section of the documentation, covered by #208.
