### ISSUE TITLE
Define error handling strategies: restart, drop 

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#17]
It should be possible to define error handling strategies.

This may vary depending on the kind of Projection. Ideally, we should have a unified way of doing that. 

Needs further exploration.

**Comment by renatocaval** [comment]
Original commend from @ignasi35 

> Another common request, when talking about head of line blocking, is a dead letter service.

**Comment by renatocaval** [comment]
Original comment from @jroper 

> Retry with timestamp of first failure captured also... we want to allow additional decisions to be made, eg, after it has been failing for 100 attempts or 10 minutes, raise an alert, or dead letter it, etc.

**Comment by patriknw** [comment]
This was added for Slick in https://github.com/akka/akka-projection/pull/82
I'll add similar for Cassandra.
