### ISSUE TITLE
Offset management API

### ISSUE THREAD

**Issue by jroper** [akka/akka-projection#172]
As a user of projections, I'd like to be able to control the offset. Some example use cases include:

* If a projection is failing on a particular event, as a quick fix to get my prod system working again (before addressing the issue properly with a fix in code that will take time), I'd like to be able to skip that event, by updating the offset store to say that offset has been successfully processed.
* If a projection for some reason gets corrupted, I'd like to be able to rebuild it by resetting the offset tracking to `NoOffset`, and replaying all events from scratch.
* I'd like to be able to query the status of my offset tracking so I can debug issues.

Of course, all of this can be done by directly interacting with the database, but given that even that will require me to expose a remote management API to stop the projections from before updating the database so that they'll pick up the change in offset when restarted, I'd rather be able to programatically do that so that I can include that functionality in my management API and just have one place to go. Currently, to programatically do that, I would have to for example copy/paste the code in `SlickOffsetStore` into my own project.

**Comment by patriknw** [comment]
I agree. We should add this kind of offset management API already in MVP.

Another type of management is to pause, resume projections, and that is covered by https://github.com/akka/akka-projection/issues/25 (not planned for MVP).

**Comment by hseeberger** [comment]
Yes, MVP please.

**Comment by PerWiklander** [comment]
I'd just like to add that a reason for rebuilding a projection could be that the projection code / db schema has changed in a newly deployed version. Any ideas on how to handle that gracefully? Today, with Lagom, we just delete the projected tables and associated row in the offset table and let everything rebuild on restart of the service, but that is in no way graceful.

**Comment by ignasi35** [comment]
@PerWiklander an alternative for Lagom users is to redeploy the code for the new read-side processor (as you mentioned, with different table schames) under a new processor name. Or even deploy a version running both the old and the new projections while the new one catches up and, later, do a new deployment with only the new processor and all queries pointing to the new tables.

Circling back to @jroper's request:

> If a projection for some reason gets corrupted, I'd like to be able to rebuild it by resetting the offset tracking to NoOffset, and replaying all events from scratch.

@jroper In that case you described it'd be up to the user to do all the DB cleanup/truncate, correct? I would not consider it a library responsiblity to cleanup before replay.

**Comment by jroper** [comment]
Here's what I'd like in this feature:

* Method to retrieve current offset for a processor by id (required).
* Method to retrieve all offsets for all processors in database (nice to have, could be done by retrieving one at a time, but for a projection status management call, typically all will just be retrieved).
* Method to update the current offset for a processor by id (required).
* Method to delete the current offset for a processor by id (nice to have, especially if retrieving all offsets for all processors is implemented, as that may return offsets for deleted processors, this would allow clean up). Could be implemented by deleting the offset if it was updated to `NoOffset`.

**Comment by seglo** [comment]
Reminds of the the Kafka Admin Client.
