### ISSUE TITLE
Distribute the consumption of events across an Akka Cluster

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#18]

**Comment by renatocaval** [comment]
Original comment from @seglo 

> It might be difficult to provide the same message delivery guarantees to send messages over cluster. Would at least once would require the reliable delivery things that Patrik is working on, or will akka streams streamrefs enable that?

**Comment by renatocaval** [comment]
In Lagom we have that already, but only for Akka Persistence Query. In a nutshell, we split the journal into virtual partitions by adding a shard number to the tags.

Since we know how many different tags we have, we start as many projections in the cluster. Each reading from one virtual partition (or tag), for instance: Event0, Event1, Event2. Three tags, three read-side projections.

They get distributed in the cluster and each projection tracks its own offset.

For Kafka, I guess we could do the same as long as we know the Kafka partitions beforehand.

This doesn't affect the delivery guarantees nor requires reliable delivery feature. It's just about having different partitions and one dedicated consumer for each of them distributed in the cluster.

**Comment by renatocaval** [comment]
Original comment from @jroper 

> Another way to think of this is providing the same functionality that Kafka consumer groups provides to consuming any arbitrary source, using Akka's distribution capabilities.

> Is the intention to move Kafka's distribution concerns into Akka? Because Kafka doesn't need this of course, out of the box you can use consumer groups to get distribution of stream consumption, the same would go for most message broker sources. Personally I'd rather let the message broker do the distribution, the message broker can probably make more intelligent decisions out of the box than Akka, plus for users, I would suspect that having their Akka Kafka consumers work the same as all their other Kafka consumers would simplify things conceptually.

**Comment by renatocaval** [comment]
Distribution should be optional and depends on the kind of source you are dealing with.

If it doesn't make sense for Kafka users, then they should just not use it.

**Comment by seglo** [comment]
> For Kafka, I guess we could do the same as long as we know the Kafka partitions beforehand.

The new Akka cluster external sharding strategy support in Alpakka Kafka provides a way of automatically retrieving the number of partitions in a Kafka topic.  This is used decide how many akka cluster shards to create and is used in the message extractor algorithm to route messages to the right shards.  You can find an example in this akka-samples project: https://github.com/akka/akka-samples/tree/2.6/akka-sample-kafka-to-sharding-scala

**Comment by renatocaval** [comment]
Yeah, I think for Kafka projections we can pretty much rely on that. Thanks for the link.

**Comment by renatocaval** [comment]
We have experimented with it in #99 and we came to the conclusion that such an addition API is not needed for now. 

When we start work on the projection control API (#25) we may need to add some extra glue code. 

For the MVP, we will only document how to integrate it with `ShardedDaemonProcess`.
