### ISSUE TITLE
Restart the consumption in case of failures using RestartSource

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#19]
Should all `Source` be wrapped with a `RestartSource` or should we let it to the user to decide?

**Comment by renatocaval** [comment]
My personal opinion on that is that we should wrap it. Projections are expected to be background process and therefore it makes sense to restart in case of failures. 

Of course, we need some backoff settings and also some means to allow users decide when it's failure or not (see #17).

**Comment by patriknw** [comment]
yes, it should. Somewhat related to https://github.com/akka/akka-projection/issues/18

**Comment by seglo** [comment]
+1 on including `RestartSource`.  It gives projections battled-tested connection handling logic for free.
