### ISSUE TITLE
Rename StatusOverserver.restarted to .failed

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#194]
The only thing we know here is that this stream stopped because of a failure. We can't no if it will restart. For instance, a user may have configured (via settings) the backoff for a limited number of retries. 

That's a detail maybe, but if we call it `restarted` and we keep using that term, we may give the wrong impression.

_Originally posted by @renatocaval in https://github.com/akka/akka-projection/pull/193_

**Comment by patriknw** [comment]
ok, I'll do that
