### ISSUE TITLE
TestKit: Re-usable in-memory TestProjection and TestSourceProvider

### ISSUE THREAD

**Issue by seglo** [akka/akka-projection#198]
There are several places in test code where we repeat ourselves and implement a `TestProjection` from scratch (for example, in `KafkaSourceProviderImplSepc` and `ProjectionTestKitSpec`, but there are others..)  It would be nice to have a programmable `TestProjection` that can be reused in our tests, as well as user tests.

https://github.com/akka/akka-projection/pull/183#discussion_r435023680

**Comment by patriknw** [comment]
When doing this we should also support the `EventEnvelope` in this TestSourceProvider, since `EventSourcedProvider` will be the most common source.

**Comment by seglo** [comment]
I've started exploring this as part of the getting started guide #270.  I'll implement the minimum there and then complete it after.

**Comment by seglo** [comment]
> When doing this we should also support the `EventEnvelope` in this TestSourceProvider, since `EventSourcedProvider` will be the most common source.

I think it makes sense to move `EventEnvelope` from `eventsourced` to `core` and bring in the persistence dependency.  The `eventsourced` project already depends on `testkit`, so there's a circular dependency.

**Comment by seglo** [comment]
It looks like `akka-persistence-query` is already included as a `provided` dep.  Should we just make it a hard dep?

**Comment by renatocaval** [comment]
I don't see why we need to change anything in `TestSourceProvider` regarding `EventEnvelope`. The `TestSourceProvider` is agnostic about what is being provided, no?

If I want to write a test using `EventEnvelope`, then can just build a `TestSourceProvider` for it. Or I can use a query directly.

**Comment by seglo** [comment]
I think `EventEnvelope` is just a useful pre-existing envelope like type that can be used in tests.  Is that why you suggested making it available to the testkit, @patriknw?

**Comment by patriknw** [comment]
I don't think EventEnvelope is general purpose. It's related to Akka Persistence, with seqNr and persistenceId.

**Comment by seglo** [comment]
This has been partially implemented in #270.  

TODO:

* Cleanup code documentation
* Add documentation and samples
* Update other tests to use the TestProjection and TestSourceProvider instead of their own custom implementations

**Comment by seglo** [comment]
I think this should target the 1.0 milestone, but not necessarily the release candidate. /cc @renatocaval

**Comment by renatocaval** [comment]
Does that make a difference for users? I thought we were only talking about our internal test infrastructure. If so, we can do it after v1.0 as well.

**Comment by seglo** [comment]
I think it's definitely useful for end users.  It lets them test handler logic in isolation without requiring the underlying db as a container/embedded/in memory service.  The tests for the getting started guide are demonstrating this.

**Comment by renatocaval** [comment]
Correct. 

Let's try to add it for v1.0, but let's not make it a blocker. We can add such an improvement on a patch release.

**Comment by seglo** [comment]
SGTM :+1:
