### ISSUE TITLE
Alpakka Kafka Projections (Consumer)

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#20]
Create projection for Alpakka Kafka Source where the offset is tracked in Kafka (committing)

**Use case:**
* reads from any Alpakka Kafka Source and commits offset on the Topic. The user only provides a Source/Flow that runs all operations and commits back to the Topic.

**Specs:**
* minimal projection only to run it in a managed and distributed fashion
* Source is Kafka, projection target is whatever the user decides
* all logic can be defined at the Source and by the user. This allows for arbitrary complexity.
* Offset is managed by Kafka, supports at-least-once and at-most-once

**Comment by ennru** [comment]
I've suggested additions to Alpakka Kafka for this in https://github.com/akka/alpakka-kafka/pull/1090

**Comment by patriknw** [comment]
Let's close this for 0.1 and work on more specific tickets for the remaining things.
