### ISSUE TITLE
Docs: scala standard library listed as a dependency

### ISSUE THREAD

**Issue by johanandren** [akka/akka-projection#203]
Not sure that is on purpose?

<img width="1264" alt="Screenshot 2020-06-05 at 13 58 14" src="https://user-images.githubusercontent.com/666915/83873740-9baa7900-a734-11ea-8963-2bd3560725c1.png">

**Comment by patriknw** [comment]
ok, but it is a dependency. Anyway, isn't this a problem for the info plugin and not akka-projection?

**Comment by ennru** [comment]
The Scala library is a dependency and this listing is provided by sbt-dependency-graph. It has always been like this... https://doc.akka.io/docs/alpakka/1.1.0/amqp.html#artifacts
