### ISSUE TITLE
StatusObserver should report progress for grouped Envelopes

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-projection#213]
### Short description

When reporting progress of a projection that used batched operations the report should include the data of all the ~evenlopes~ _envelopes_ .

### Details

`StatusObserver#progress` takes only a single `Envelope` as an argument. When batching envelopes so only the last offset of the batch is committed, [only the last envelope is reported](https://github.com/akka/akka-projection/blob/8847dfa08711f88d66a0be4a2c61081933d66dc6/akka-projection-cassandra/src/main/scala/akka/projection/cassandra/internal/CassandraProjectionImpl.scala#L296-L303). If it took a collection the group size would be available to `StatusObserver` implementations.

PS: `StatusObserver#error` also takes a single envelope (and the first and last offsets of the error'ed batch) but I don't think it makes sense to provide all the envelopes on that case.

**Comment by patriknw** [comment]
Depends on the purpose of the `progress` method. I realize that the name and doc doesn't convey that the original intent was to report progress of offset storage. We should fix that by changing the name to `offsetProgress` and clarify docs. With that scope current signature makes sense also for grouped projections.

Then we should probably add `beforeProcess` and `afterProcess` for tracking fine grained processing progress for each envelope. Those can also be called for each envelope in a group.

**Comment by ignasi35** [comment]
With #216 in the issue list, the scope for this issue is only reviewing documentation of `progress()`.

**Comment by ignasi35** [comment]
Finished in #330 and #343
