### ISSUE TITLE
Explain caveats using Kafka with Slick exactly-once

### ISSUE THREAD

**Issue by seglo** [akka/akka-projection#214]
See https://github.com/akka/akka-projection/issues/98 for inspiration.

**Comment by renatocaval** [comment]
can be mitigated by increasing the offset fetch delay.

**Comment by seglo** [comment]
Here's the relevant section for the read offset delay in the KafkaSourceProvider: https://github.com/akka/akka-projection/pull/266

And the "revoked partition management" to filter out in-flight messages from revoked partitions during a consumer group rebalance (among other things, I put a lot of things in this PR): https://github.com/akka/akka-projection/pull/183
