### ISSUE TITLE
StatusObserver fine grained callbacks

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-projection#216]
`StatusObserver` should include a callback invoked anytime a new envelope is ready to start processing (invoked immediately before extracting the offset from the envelope).

**Comment by ignasi35** [comment]
Just seen @patriknw's proposal in https://github.com/akka/akka-projection/issues/213#issuecomment-641796604:

> Then we should probably add `beforeProcess` and `afterProcess` for tracking fine grained processing progress for each envelope. Those can also be called for each envelope in a group.

**Comment by patriknw** [comment]
Yes, before and after is most flexible, I guess.

**Comment by ignasi35** [comment]
Solved in #330
