### ISSUE TITLE
Alpakka Kafka Projections (Producer)

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#22]
**Use case:** 
* consume from any Source and publish the events in Kafka. This is the equivalent of Topic Producers in Lagom. 

**Specs:**

* Offset is managed by the chosen DB technology (Cassandra/JPA/Slick) or by committing to Kafka if the Source is from Kafka, supports at-least-once and at-most-once
* Publish can be done on a mapAsync, needs https://github.com/akka/alpakka-kafka/issues/500 
* Publish is done using Alpakka Flow/Sink: https://doc.akka.io/docs/alpakka-kafka/current/producer.html#choosing-a-producer

**Comment by ennru** [comment]
The Alpakka Kafka `SendProducer` is now merged https://doc.akka.io/docs/alpakka-kafka/snapshot/send-producer.html

**Comment by patriknw** [comment]
Documented usage in https://github.com/akka/akka-projection/pull/135

**Comment by patriknw** [comment]
When we have the Flow based projections we can also show the Flow based Kafka producer.

**Comment by seglo** [comment]
> When we have the Flow based projections we can also show the Flow based Kafka producer.

If Alpakka Kafka could support produce only transactions then we could produce on the user's behalf as part of #94.

**Comment by patriknw** [comment]
Created issue https://github.com/akka/akka-projection/issues/143 for the producer Flow.
Let's close this ticket for 0.1
