### ISSUE TITLE
DRY javadsl/scaladsl ProjectionTestKitImpl

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#220]
Noticed much non-trivial repetition in the javads/scaladsl implementations. Would be good to delegate or share common impl.

**Comment by seglo** [comment]
Will implement in #198.  We can keep this task to update internal test suites.

**Comment by patriknw** [comment]
Many testkit things were improved by the merged PRs, but what I intended with this issue was not fixed. I have done that in PR https://github.com/akka/akka-projection/pull/392

**Comment by seglo** [comment]
Addressed in #392.
