### ISSUE TITLE
Add extractCreationTime to SourceProvider

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-projection#232]
The supported source providers (eventsourced and kafka) provide envelopes that include a creation time (Kafka, almost does).

Adding a function `def extractCreationTime(envelope: Envelope): Option[Long]` to `SourceProvider` so that the value is extracted if available will unblock computing the event Resitence Time (aka total Latency).

I did a quick experiment in https://github.com/akka/akka-projection/pull/230/commits/a4e17e978b010ee82cc02385be70b6887166a827

**Comment by seglo** [comment]
:+1:

We could make this a trait we can mix in with a `SourceProvider` as needed, instead of returning the optional.  Similar to thinking in `VerifiableSourceProvider` #199

**Comment by patriknw** [comment]
good to add that
