### ISSUE TITLE
SlickOffsetStore and JdbcOffsetStore must be compatible with each other

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#234]
Users may mix Slick and JDBC projections (or move from one to the other). The offset store should be compatible, better to replace the Slick one by the JDBC or make it a thin layer on top of it.

Discussion tarted here: https://github.com/akka/akka-projection/issues/68#issuecomment-643251687_

**Comment by patriknw** [comment]
sounds good that we use the same schema definition

**Comment by patriknw** [comment]
Was this fixed?

**Comment by ignasi35** [comment]
> Was this fixed?

I think this is fixed. After a manual review of code and docs both Slick and JDBC implementations use the same offset store schema for each supported dialect.

**Comment by renatocaval** [comment]
> I think this is fixed. After a manual review of code and docs both Slick and JDBC implementations use the same offset store schema for each supported dialect.

I don't think it's true. MS SQL uses a different type for the timestamp column. When I did the JDBC impl, I picked exactly the same schema each time. Except for the MS SQL Server, for which I need to add some tweaks. 

Moreover, the goal of this issue was not to verify, but make sure they involve together and that the schema shown on the docs is derived from what we use in code.

If we isolate the createIfNotExist statement to a common place, we can give that guarantee. We can go down to plain SQL, instead of using Slick generation. Then we can prove that the DDL is also good for Slick since we have tests that exercise all the DB variants.

**Comment by ignasi35** [comment]
> I don't think it's true. MS SQL uses a different type for the timestamp column. When I did the JDBC impl, I picked exactly the same schema each time. Except for the MS SQL Server, for which I need to add some tweaks.

 - In that case, the documentation in `slick.md` for MSSqlServer is wrong. I'll look into that.

> Moreover, the goal of this issue was not to verify, but make sure they involve together and that the schema shown on the docs is derived from what we use in code.

There are two tasks there:

 - make the information in docs be generated from code
 - exercise a test where the JDBC and the Slick implementations interoperate on the same table

> If we isolate the createIfNotExist statement to a common place, we can give that guarantee. We can go down to plain SQL, instead of using Slick generation. Then we can prove that the DDL is also good for Slick since we have tests that exercise all the DB variants.


OK, I see... I'll extract a separate project both the `a-p-jdbc` and `a-p-slick` depend on where the table definitions reside. Each implementation and docs, can then read from there. This will make docs a bit less readable since we want table names parameterized (I'll see what I can get).

**Comment by renatocaval** [comment]
> exercise a test where the JDBC and the Slick implementations interoperate on the same table

I don't think this is needed. If the Slick tests used the create-statements from JDBC, we are good.

**Comment by ignasi35** [comment]
Solved in #348
