### ISSUE TITLE
Handle recovery and skip in flow failures

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-projection#239]
Flow-based handlers could also support `HandlerRecoveryStrategy`'s. 

~It is possible for users to combine use the `withRestart` using the overload that includes the `maxRestart` parameter but it's lacking support to `skip` (I think all other strategies `HandlerRecoveryStrategy` are already covered).~ _`withRestart`_ methods in the projection factory methods wrap the `Source`, not the user flow.

Refs #119

**Comment by patriknw** [comment]
The main purpose of `HandlerRecoveryStrategy` is to retry the same envelope if fails without restarting the entire stream (Projection). If we would wrap the user flow with some restart it would not retry with same envelope, and there could also be other envelopes in flight in the flow that would be lost.

I don't think we should have any built in retry mechanism for flow based but only fall back to the full restart of the projection, which is handled by `RunningProjection.withBackoff(() => mappedSource()`

**Comment by ignasi35** [comment]
The flow API in akka-projections is quite similar from the user point of view to Lagom's broker subscriber. There's a [long standing issue](https://github.com/lagom/lagom/issues/734) to imrpvoe the lagom API in a way that helps avoid head-of-line blocking. 

I agree with you that retrying should better be solved with a full stream restart, but the flow API could use a mechanism to _skip_ messages. 

I've edited the subject to reflect that `skip` is also missing.

**Comment by patriknw** [comment]
>  but the flow API could use a mechanism to skip messages

ok, but it is already possible to skip messages by filtering. It will not store that skipped offset but when next offset is passed through that offset will be stored. As long as you have some more envelopes that are not skipped that should be enough.

It's also possible to just emit a `Done` (with its context) to skip.

Maybe I misunderstand what is needed?

**Comment by patriknw** [comment]
> but the flow API could use a mechanism to skip messages

@ignasi35 Do you still think we have missed anything here? See [my comment above](https://github.com/akka/akka-projection/issues/239#issuecomment-643980086).

**Comment by ignasi35** [comment]
> @ignasi35 Do you still think we have missed anything here? See [my comment above](https://github.com/akka/akka-projection/issues/239#issuecomment-643980086).

No, looking as the `Flow` handler as a power-user API it's all good. We can close it.
