### ISSUE TITLE
Document limitation of StatusObserver when used with FlowHandlers

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-projection#271]
(from https://github.com/akka/akka-projection/pull/230#discussion_r444290107 )

### Short description

`FlowHandlerStrategy` doesn't use a `HandlerRecoveryImpl`. As a side effect, `StatusObserver#error` is not invoked in case of errors processing an envelope.

Related to #239

**Comment by patriknw** [comment]
I think it's fine to skip it for flow based handler. The original purpose of `error` was to indicate that it was "stuck" in retrying. `failed` will anyway be called before restart.

**Comment by ignasi35** [comment]
Makes sense. We can add a note in the documentation for the edge cases.

**Comment by renatocaval** [comment]
I'm renaming this issue since we will make it a documentation only task.
