### ISSUE TITLE
SlickOffsetStore does not match "PROJECTION_KEY" for provided schema with Postgres

### ISSUE THREAD

**Issue by tomp4l** [akka/akka-projection#275]
### Versions used 

Akka version: 2.6.6
Akka projections: 0.2

### Expected Behavior

When recovering a SlickProjection the handler is started from after the stored offset. The schema in the documents at https://doc.akka.io/docs/akka-projection/current/slick.html#schema is used as follows:
```SQL
create table if not exists "AKKA_PROJECTION_OFFSET_STORE" (
  "PROJECTION_NAME" CHAR(255) NOT NULL,
  "PROJECTION_KEY" CHAR(255) NOT NULL,
  "OFFSET" CHAR(255) NOT NULL,
  "MANIFEST" VARCHAR(4) NOT NULL,
  "MERGEABLE" BOOLEAN NOT NULL,
  "LAST_UPDATED" TIMESTAMP(9) WITH TIME ZONE NOT NULL);
```

### Actual Behavior

All the events from the journal are replayed. This seems to be because of using the `CHAR(255)` data type the string is read padded with whitespace. This then fails the equality check at: https://github.com/akka/akka-projection/blob/b1a044e1ab13e2a365ce1b160bf9bc035e5bce37/akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickOffsetStore.scala#L56

Potential fixes are changing the data type in provided schema to `VARCHAR` or `TEXT` which I have confirmed fixes the issue. The other solution would be to trim the whitespace although I'm not sure exactly where would be best to handle this (inside ProjectionId or outside).

I'm happy to help with a PR if I can be pointed in the right direction, I'm unsure how I would add a test case to cover this specifically though although maybe it's just a case of updating the docs? I'm assuming using Slick to create the schema will lead to it not using the `CHAR` data type although I have't tested.

**Comment by renatocaval** [comment]
@tomp4l, I'm have been bitten by this recently. This is now fixed and will be release (most probably) today.

**Comment by renatocaval** [comment]
Fixed in https://github.com/akka/akka-projection/pull/263

See https://github.com/akka/akka-projection/pull/263/files#diff-2821652f0bfc9fa3a21e69d81f5513fbR75-R77

**Comment by renatocaval** [comment]
Btw, @tomp4l thanks for the detailed report. We had already spotted it, but otherwise the fact that you pinpointed exactly where the problem was is of huge help.

**Comment by tomp4l** [comment]
@renatocaval No problem, thanks for confirming the fix!
