### ISSUE TITLE
Review StatusObserver#progress semantics

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-projection#277]
(as discussed in https://github.com/akka/akka-projection/pull/230#discussion_r445647154) 

`StatusObserver#progress` is currently `Called when the envelope has been processed and corresponding offset stored`, this is different from `Telemetry` which provides both `afterProcess` and `onOffsetStored` to support all three `OffsetStrategies`.

Instead, `StatusObserver#progress` should use the same semantics of `Telemetry#onOffsetStored` even in `at-most-once` where the invocation happens before the envelope started processing.

**Comment by patriknw** [comment]
We'll keep the StatusObserver and Telemetry separate, but I would still like that we aligned semantics, naming and call sites as much as possible for these reasons:
* less Future map/flatMap means better performance (same call sites)
* easier for us to understand/maintain if naming and semantics are aligned

**Comment by patriknw** [comment]
Related to https://github.com/akka/akka-projection/issues/213

**Comment by ignasi35** [comment]
Finished in #343
