### ISSUE TITLE
Review the usage of Supplier and akka.japi.function.Creator in Java API

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#317]
We are using a mix of java `java.util.function.Supplier` and `akka.japi.function.Creator` in the Java API. I don't think there is a reason for that. 

Ideally, we should review this and fix before we cut `v1.0.0` to avoid breaking the API.

**Comment by ignasi35** [comment]
I think the decision was to prefer JDK APi over Akka-specific, right? So `Supplier` preferred over `Creator`?

**Comment by renatocaval** [comment]
Correct, unless we need to throw exceptions, then we need to use `Creator`

**Comment by raboof** [comment]
> I don't think there is a reason for that.

Indeed the main difference is that you're allowed to throw checked exceptions from a `akka.japi.function` body, which can be convenient (if the code that this function is passed to actually handles that), and has variance defined. Those 2 differences make it more consistent with the scala `Function1` counterpart. On the other hand, `java.util.function` is of course more familiar to Java users.

I don't think we ever nicely wrote down how to choose between `akka.japi.function` and `java.util.function` - I made a start at https://github.com/akka/alpakka/pull/2359/files

**Comment by renatocaval** [comment]
Done in #345
