### ISSUE TITLE
Ensure Projections are stopped when CoordinatedShutdown is triggered

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#33]

**Comment by patriknw** [comment]
Not sure we need to do much here unless we want to hook in some more graceful (draining) stopping. They will be stopped automatically when the ActorSystem is stopped since they are actors/streams.

**Comment by ignasi35** [comment]
I think the task here is to document the recommended way to stop the projections, especially when deployed as cluster daemons.


Related to https://github.com/lagom/lagom/issues/2427

**Comment by renatocaval** [comment]
> unless we want to hook in some more graceful (draining) 
Yes, that's what I had in mind.

**Comment by renatocaval** [comment]
For the moment, we can consider that this is not much needed. 

The recommended way to run a projection is to use `ShardedDaemonProcess` and declare the `ProjectionBehavior.Stop` as the stop message. That will gracefully stop the stream. 

User running the `ProjectionBehavior` directly won't have that functionality tough.

**Comment by patriknw** [comment]
Good, then we close this.
