### ISSUE TITLE
Disable parallelExecution in Ci (and other env's with limited resources)

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-projection#333]
`parallelExecution` in sbt speeds up execution of tests if the environment where the process runs has plenty of resources. Travis CI is very limited.

Also, the gains in time using `parallelExecution` in TravisCI are negligible compared to download times.

Running sequentially may help stabilize the build in travis. 

Extra bonus: running tests sequentially means captured logs in case of test failure are not polluted by concurrent tests.

**Comment by renatocaval** [comment]
I'm fine to remove it, we don't need to remove it only in CI, it will complicate the build. 

Locally, I most often build only the stuff I'm working on using `sbt ~akka-projection-{module}/testQuick`

**Comment by ignasi35** [comment]
> Locally, I most often build only the stuff I'm working on using `sbt ~akka-projection-{module}/testQuick`

Using parallel execution, there is some improvement when running locally that's why I didn't raise this earlier. I did some tests and `akka-projection-jdbc` runs 3x faster when in parallel (on my machine). But I see your point.

**Comment by renatocaval** [comment]
Done in #322
