### ISSUE TITLE
Prefer a stateless handler on the GettingStartedGuide

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-projection#350]
See https://github.com/akka/akka-projection/pull/270#discussion_r456293277

**Comment by renatocaval** [comment]
I went through the Cassandra example in the Getting Started Guide, I my gut feeling is that we should make it much simpler than it is now. I would prefer a simple projection example, one event stream, one table to write the data using `at-least-once`. No volatile var to support logging and no stateful handler.

The stateful handler is a special case that is already covered in the documentation. That said, we can recude the "Getting Started Guide" to one use case, the most common one. Its function it to illustrate, step by step, how to setup a projection. Therefore we can keep it to a minimal example.

**Comment by seglo** [comment]
Ok.  To avoid too much churn on the example I would propose we just keep the intermediate projection of "current cart state".  Instead of projecting to a new table on checkouts, we could just update that one.  That would be believable use case I think.

The `StatefulHandler` is useful in this case because it demonstrates refreshing state after a failure.  We could manage initialization of state from the projection table another way, but the `StatefulHandler` seemed appropriate given its `initialState` method.  If we drop the management of state then the example ceases to make sense.

**Comment by seglo** [comment]
I'd like to take a crack at simplifying the example along these lines, unless anyone has an objection or alternative idea?

**Comment by ignasi35** [comment]
> ignasi35 assigned seglo now

:-)

**Comment by renatocaval** [comment]
@seglo, I think the most common case for a projection is to, for each event, insert or update a model on a table without keeping state in the handler. I don't think we should have a projection with state in a "Getting started guide". 

The handler is now fetching all rows, keeping it on a map that is then passed to the `process` method. We update one entry on that Map and then we flush it to the DB. Why is that needed? 

I think such a `StatefulHandler` makes sense if we are keeping a total count. In that case, you want to have a single writer (thus one projection instance) and keeps a pre-loaded instance of the model in memory. On each event, you don't need to load it from DB (the state works as a cache) and you only do updates. That's not the case of an event handler that is updating the cart state by id.

**Comment by seglo** [comment]
> @seglo, I think the most common case for a projection is to, for each event, insert or update a model on a table without keeping state in the handler. I don't think we should have a projection with state in a "Getting started guide".

I guess it's subjective, and I don't have any data to point to, but I would argue that any interesting streaming operation/projection is will maintain state in some manner, whether that state is local to processing or somewhere else.  That said, I agree that the getting started guide should at least start with a simpler example that doesn't require state management in the handler itself.  Possibly state could be added as an extra step, or omitted altogether.

> I think such a `StatefulHandler` makes sense if we are keeping a total count. In that case, you want to have a single writer (thus one projection instance) and keeps a pre-loaded instance of the model in memory. On each event, you don't need to load it from DB (the state works as a cache) and you only do updates. That's not the case of an event handler that is updating the cart state by id.

That's the thing, it is used as a cache.  The original purpose of maintaining the state was to be able to write the full shopping cart contents to the projection table when a checkout is received, without having to read state from the database first.  I think I can probably achieve the same goal without having two tables though, and possibly without the `StatefulHandler`.  I'll play with it and maybe ping you and Ignasi before I spend too much time on it.

**Comment by renatocaval** [comment]
Done in #372
