### ISSUE TITLE
Review git fetch --unshallow settings

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#38]
This is required (as the comment states) as dynver and MiMa can get problems without it (Only shows when there is a lot of commits between versions).

_Originally posted by @ennru in https://github.com/akka/akka-projection/pull/30_

**Comment by ihostage** [comment]
I think it related to https://docs.travis-ci.com/user/customizing-the-build#git-clone-depth
> Some operations on the repository, such as common automated code review scripts (e.g. Pronto for Ruby), may fail due to the limited git clone depth, not being able to access all the objects in the repository. Removing the depth flag, or running `git fetch --unshallow` might solve the issue.
 
Need to remove depth by:
```
git:
  depth: false
```

**Comment by ennru** [comment]
Fixed with #40
