### ISSUE TITLE
Getting Started Guide: source of EventGeneratorApp

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#386]
We can't expect users to clone akka-projection, so EventGeneratorApp must be inluded as source in getting-started/running.html

**Comment by seglo** [comment]
Do we need to provide a Java version?

**Comment by patriknw** [comment]
> Do we need to provide a Java version?

I'm afraid we have to, since a .scala would require a different build for maven users and they would not know how to build and run it.
