### ISSUE TITLE
Failed: JdbcProjectionTest exactlyOnceShouldRestartFromPreviousOffset

### ISSUE THREAD

**Issue by seglo** [akka/akka-projection#397]
```
<-- [akka.projection.jdbc.JdbcProjectionTest: exactlyOnceShouldRestartFromPreviousOffset] End of log messages of test that failed with Expected exception
[info] - exactlyOnceShouldRestartFromPreviousOffset *** FAILED ***
[info]   java.lang.AssertionError: Expected exception
[info]   at org.junit.Assert.fail(Assert.java:88)
[info]   at akka.projection.jdbc.JdbcProjectionTest.exactlyOnceShouldRestartFromPreviousOffset(JdbcProjectionTest.java:259)
```
https://travis-ci.com/github/akka/akka-projection/jobs/371418704#L564

This may have something to do with non-integration tests not running in parallel.  I debated whether the H2 tests should belong in integration tests config or not, and opted to keep them as unit tests since they're fast.  It may be worth experimenting if `parallelExecution := false` is the issue here.

**Comment by patriknw** [comment]
another https://travis-ci.com/github/akka/akka-projection/jobs/372959526

**Comment by renatocaval** [comment]
I have seen this test failing a few times in the last days. We should reserve some love for it on the next gardening round.

**Comment by seglo** [comment]
https://travis-ci.com/github/akka/akka-projection/jobs/388109294#L552

**Comment by seglo** [comment]
I'll look into this today.

**Comment by ignasi35** [comment]
Sorry, I've seen a fail but it's on `atLeastOnceShouldRestartFromPreviousOffset` (not `exactlyOnceShouldRestartFromPreviousOffset`).
