### ISSUE TITLE
Consider the introduction of EventHandler trait

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#43]
Doesn't look too bad for this simple event handler, but worth exploring.

I think a class also encourages that the handler can have state. That's ofc possible with a function also, but less obvious that it s safe since most (should) think a function is stateless. We could always provide a convenience implementation of such class that just wraps a function.

_Originally posted by @patriknw in https://github.com/akka/akka-projection/pull/35_

**Comment by patriknw** [comment]
I'll continue by adding similar for Cassandra
