### ISSUE TITLE
JDBC createIfNotExists may fail when index already exists

### ISSUE THREAD

**Issue by octonato** [akka/akka-projection#488]
The JDBC createIfNotExists utility does a good job to create the tables, but it will fail with 
`PSQLException: ERROR: relation "PROJECTION_NAME_INDEX" already exists` on creating the index if it already exists. 

The create of the table is protected with a `IF NOT EXISTS`, but there is no protection for the index.

**Comment by hseeberger** [comment]
Notice that the subsequent creation of the PK also might fail. Better fold it into the creation of the table.

**Comment by octonato** [comment]
Solved in #490
