### ISSUE TITLE
ProjectionManagement.clearOffset never completes for not started projection

### ISSUE THREAD

**Issue by hseeberger** [akka/akka-projection#494]
When calling `ProjectionManagement.clearOffset` for some projection before actually starting it, the returned future never completes. While it might seem odd to clear the offset before starting the projection, I think there is a sensible scenario: when the projection writes to a database and the respective database schema is evolved and the respective tables dropped and created, the offset should be cleared before starting the projection. Somewhat like restarting an eventsourced actor where the events (and snapshots) are replayed before it will process any commands.

**Comment by hseeberger** [comment]
If `clearOffset` would not "hang", the following were possible:

``` scala
      ...
      // Clear the offset of the user projection if necessary
      val offsetCleared =
        if (schemaChanged) {
          log.info(
            s"Clearing projection [${UserProjection.projectionId}] offset, because schema changed"
          )
          ProjectionManagement(system).clearOffset(UserProjection.projectionId)
        } else
          Future.successful(Done)

      // Start the user projection after potentially clearing the offset
      offsetCleared.foreach { _ =>
        log.info(s"Starting projection [${UserProjection.projectionId}]")
        ClusterSingleton(system).init(
          SingletonActor(
            ProjectionBehavior(
              UserProjection(databaseConfig, JdbcReadJournal.Identifier, userRepository)(system)
            ),
            UserProjection.projectionId.id
          )
        )
      }
```

**Comment by patriknw** [comment]
I agree, this should be fixed. How urgent is this? Do you have a workaround?

**Comment by hseeberger** [comment]
Not urgent. Changing the order (start projection first, then clear the offset) during system bootstrapping probably works as well, because there are other things that need to be initialized before the system is ready to take any requests – until then the offset clear should long have happened.

**Comment by patriknw** [comment]
Let's find some time for this in upcoming gardening.

**Comment by patriknw** [comment]
@hseeberger I looked into how we implemented the ProjectionManagement, and realized that this would be difficult to fix.

The management commands (such as the clearOffset) are running via the ProjectionBehavior itself, so if the Projection isn't initialized (started) it will not run. I'm pretty sure you would see this as a timeout exception, configured with `akka.projection.management.operation-timeout` (default 10s).

The reason we have implemented it in this way and not just modifying the database directly is that we want to coordinate these commands with in-flight processing in the Projection. The Projection is first stopped, the mgmt action is performed, and then the Projection is started again.

The Projection instances can run anywhere in the Cluster so this is implemented with the Receptionist (pub-sub).

I think we are getting closer and closer to an official request for implementing the Start/Pause/Stop management in https://github.com/akka/akka-projection/issues/25
With that in place the we could support starting a Projection in paused mode.

**Comment by patriknw** [comment]
Let's look at this again, since it mentions start/stop that has been implemented.

**Comment by patriknw** [comment]
This still has the same fundamental problem. The management commands are handled by the running projection instances, so it's not possible to pause before starting. Introducing some other way to write to the db on the side may cause confusion and trouble since the projection might be running but it has a different state in the management table.

The workaround is to update the database table yourself for these kind of update scenarios. Set the `paused` column in `akka_projection_management` table.

Closing without action.
