### ISSUE TITLE
Configure sbt-header for intergration tests

### ISSUE THREAD

**Issue by octonato** [akka/akka-projection#501]
Integration test files are not included in headerCheck/headerCreate

_Originally posted by @octonato in https://github.com/akka/akka-projection/pull/500#discussion_r555898283_

**Comment by octonato** [comment]
For info, the sbt-header docs mention that it should work when using `It` or `MultiJvm`, but that's not what is being observed. 

https://github.com/sbt/sbt-header#adding-headers-to-files-in-other-configurations

**Comment by seglo** [comment]
Did you try running it in those scopes explicitly?  i.e. `it:headerCreate`

**Comment by octonato** [comment]
> Did you try running it in those scopes explicitly? i.e. it:headerCreate

Yep, I did. And sbt don't even over code completion. It does for `compile:header<TAB>` and `test:header<TAB>` for instance. But shows nothing for `it`. The is really something odd with it.
