### ISSUE TITLE
Projection Telemetry SPI

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-projection#52]
(edited the list of desired metrics)

### Short description

Providing an SPI so projection implementation can raise certain events for 3rd party tooling to measure and report data to monitoring tools.

### Details

Given the nature of a projection, the first idea that comes to mind is to measure "Wait, Service, and Residence Time" (as described in [The Essential Guide To
Queueing Theory](https://www.percona.com/live/17/sites/default/files/the-essential-guide-to-queueing-theory.pdf), thanks @seglo for the reference). Summing up:

 - `Waiting Time`: time the element spent on the queue
 - `Service Time`: time the element spent being processed (since removed from the queue until readable by a read-side thread)
 - `Residence Time`: total time in the system (the sum of Waiting and Service times)

`akka-projection` can't promise to deliver `Wait Time` since it's dependant on each queuing technology to add a timestamp of the instant when the element was enqueued. Still, the SPI could include the necessary methods for custom implementations of `akka-projection` so the measure is taken when the data is available.

#### Getting more details

Once the user is familiar with "Wait, Service, and Residence Time" there are other pieces of relevant information to add to the measures so more accurate filtering in the monitoring tools helps gain more insights.

1. First, we want counts of elements successfully processed

2. Then, a rate of failures (failures on the stream per unit of time) and information about the cause, context, etc...

3. Then we want metadata for the above times, counts and rates. ~A tuple `name` and `key` is a pair of String uniquely identifying a worker consuming a partitioned/sharded queue~ (edit: _see `ProjectionId`_ ). This is useful to detect when a particular processor is slow as opposed to a fast one; or when a partition is very hot (meaning the partitioning strategy is not well balanced); or even there's a bug in the code causing a head-of-line issue.

4. The metadata introduced in `3.` could be extended, when available, to add the event (sub)type since each event type runs different code.

5. In some scenarios, the `Service Time` could be too coarse and providing means for more fine-grained measures (e.g. name a portion of the stream and measures only that)  to more accurately detect hotspots.

5.1. When batching the offset storage operation (only save one offset every *n* messages) we need to distinguish the processing time from the time-until-committed.

---------------------------------------------------------------

## Scope

 * *MUST HAVE*: `Service Time`, count of successfully processed (`1.`), rate of failures (`2.`), and `name`/`key` metadata (`3.`). The SPi must support providing this data.

 * *NICE TO HAVE*: named portions of `Service Time` (`4.` and `5.`), `Wait Time` and `Residence Time`. So we could provide the SPI so implementations provide that data when available.

**Comment by ignasi35** [comment]
Telemetry using Cinnamon has two steps:

1. (compulsory) create the instruments collect measures and the backends to report the data.
2. (optional) manipulate bytecode to inject the creation and usage fo the instruments

With minor improvements on `StatusObserver` it may be possible to implement telemetry without needing (1). This is a soft-goal.

**Comment by ignasi35** [comment]
Another factor to take into account is when to report each metric.

For example, when running an `at-least-once` projection, the success counter should only be updated after the offset is committed. This means the number of successfully processed events will be eventually consistent with the data accessible on the read-side tables.

Similarly, also when running an `at-least-once` projection, we may only report the `time-to-process` metric (time spent on user code processing the event) once the offset is committed. This means that an event that was retried multiple times would only report `time-to-process` on the last attempt. But,  it's probably OK to report the `time-to-process` measurements as soon as they are available even if that means reporting duplicates because time metrics are presented as histograms.

When moving on to grouped metrics, if we measure the `time-to-process` a batch and report only that time measurement, the dashboards will be useless. Instead, the measurement should also include the number of items in the batch/group so that the measurement can be (1) amortized and (2) reported _n_ times.

**Comment by patriknw** [comment]
Closing this for 0.3, and we can follow up in other issues
