### ISSUE TITLE
Offset serialization

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#60]
Offset is stored as `String` + manifest to support different offset types. That is a fixed set of types.

@ignasi35 questioned this

> Why is the offsetStore responsible to handle the offset types/manifests?
>
> Could readOffset have an extra argument offsetDeser: (ByteString, String) => Offset so the it's not responsibility of the offset store to manage deserialization.

I think the background reason for this was to make it human readable for back office tooling.

**Comment by renatocaval** [comment]
Yes, that was the main goal. Keep it human readable. We can (and should) extract this to utility class so it can be used by all offset store implementations. 

Alternatively, we could provide the means for users to define their own mapping, but not really need for MVP.

**Comment by patriknw** [comment]
Extraction to utility in https://github.com/akka/akka-projection/pull/65

**Comment by ignasi35** [comment]
> Yes, that was the main goal. Keep it human readable. We can (and should) extract this to utility class so it can be used by all offset store implementations.
> 
> Alternatively, we could provide the means for users to define their own mapping, but not really need for MVP.

Agree o all.

On my orginal comment I used the signature `offsetDeser: (ByteString, String) => Offset` but you're both right in that `offsetDeser: (String, String) => Offset` is prefereable..

**Comment by patriknw** [comment]
Good, then I'm closing this.
We can open new issue if/when there is a need for custom offset types.
