### ISSUE TITLE
SlickProjection + handler that is not using db

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#68]
* Using SlickProjection for managing the offset, but the event handler is not using the db, or not the same db
* `handler: Envelope => Future[Done]`
* This would be at-least-once or at-most-once

**Comment by renatocaval** [comment]
As a Slick user, I can do the following: 

```scala
val hander: Envelope =>  DBIO[Done] = { enveloper => 
	DBIO.fromFuture(someOtherDbCallReturningFutureDone)
}
```
or 

```scala
val hander: Envelope =>  DBIO[Done] = { enveloper => 
	DBIO.successful(someOtherDbCallReturningDone)
}
```

We could have a thin-layer to restrict this to only at-least-once or at-most-once cases, but I don't think it's much necessary.

**Comment by patriknw** [comment]
I see. As a non-Slick user, I didn't know. 😄 

Let's keep this ticket and document that usage or at that point decide if we need the convenience to hide Slick for that kind of usage.

**Comment by patriknw** [comment]
With the new InternalProjection structure it's simple to add support for the Future based Handler. On the other hand we should promote the JdbcProjection for this scenario when the user is not using Slick anyway.

**Comment by renatocaval** [comment]
I can imagine the situation in which users are using many different Slick projections. Some using exactly-once and others using at-least-once. 

If you have already a Slick database configured, you will prefer to it instead of managing another JDBC connection pool and implementing a `JdbcSession`.

Another import part is that we want the Slick and the JDBC data store to be the same. But that's another ticket.

**Comment by seglo** [comment]
I think it would be common to project into another non-JDBC technology, so it would be weird to force users to return a DBIO when they're making async calls to them.

:+1: for a Slick handler that's `Envelope => Future[Done]`

**Comment by patriknw** [comment]
let's include that, since it's rather trivial

**Comment by renatocaval** [comment]
I just realised that although this is trivial to add, we will need some extra methods qualifiers. This is because we now have a handler factory (ie: function from `() => Handler`). 

I thought we could simply overload the `atLeastOnce` method to receive either a `SlickHandler` or an async `Handler`, but after erasure their are the same. 

We will need something like `atLeastOnceAsync`. 

Same applies for the JDBC variant.

**Comment by renatocaval** [comment]
@patriknw / @seglo 

Before we dig into this, one extra observation that could help us in adding different kinds of handlers.

I realised that we have two kinds of `exactly-once` and two kinds of `at-least-once` and only the shape of the handler changes. Actually three if we consider `at-most-once`, but not relevant for the topic here.

* `exactly-once` for single or grouped transactional handlers
* `at-least-once` for single async handler or Flow handler. A single transactional handler can be adapted to an async one. 

The following is a suggestion that although impactful will open the doors, I believe, to increased modularity. It will require a builder, but I think it will be minimal.

```scala
atLeastOnce(
  .., 
  ..,
)
.withAsyncHandler( /* async handler */)
.withGroupedAsyncHandler()
.viaFlow(...)
.withHandler() // only available for JDBC/Slick


exactlyOnce(
  ..,
  ..,
)
.withHandler() // transactional
.withGroupedHandler() // transactional

```

The `with` methods and `viaFlow` close the builder blocking the addition of any other handler. 

It make it explicit which sematics we are choosing. Then which handling strategy. 

Btw, the grouped one is confusing, for Cassandra is at-least-once, for Slick and JDBC it's exactly-once.

**Comment by patriknw** [comment]
I don't think that is good. I see no problem with having a bunch of methods. Works well with IDE code completion. Builder style is great for optional things, but the handler is mandatory and adding that via builder is just extra exploration to find it.

> Btw, the grouped one is confusing, for Cassandra is at-least-once, for Slick and JDBC it's exactly-once.

I don't think that is confusing. Cassandra can't have exactly once, so it stores the offset immediately after processing (at-least-once). For Slick and JDBC one would of course want to use exactly-once unless looking for the performance advantage of batching the offset storage. For grouped that batching occurs before the handler, so no point in having double batching.

**Comment by renatocaval** [comment]
> Works well with IDE code completion. Builder style is great for optional things, but the handler is mandatory and adding that via builder is just extra exploration to find it.

That's indeed true
