### ISSUE TITLE
Failed: SlickProjectionSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-projection#768]
https://github.com/akka/akka-projection/actions/runs/3821827370/jobs/6501364517

```
[info] - must restart from previous offset - handler throwing an exception, save after 2 *** FAILED *** (316 milliseconds)
[info]   check: last seen offset is 2L The Option on which value was invoked was not defined. (SlickProjectionSpec.scala:946)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.OptionValues$Valuable.value(OptionValues.scala:114)
[info]   at akka.projection.slick.SlickProjectionSpec.$anonfun$new$130(SlickProjectionSpec.scala:946)
[info]   at org.scalatest.Assertions.withClue(Assertions.scala:1065)
[info]   at org.scalatest.Assertions.withClue$(Assertions.scala:1052)
[info]   at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.withClue(ScalaTestWithActorTestKit.scala:31)
[info]   at akka.projection.slick.SlickProjectionSpec.$anonfun$new$124(SlickProjectionSpec.scala:945)
```

Logs with more details
[6_Run tests with default Scala and Java 1.17.0.txt](https://github.com/akka/akka-projection/files/10331197/6_Run.tests.with.default.Scala.and.Java.1.17.0.txt)

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/4439105497/jobs/7791087402#step:6:549

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/4831307274/jobs/8608578140?pr=876#step:6:636

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/4911721799/jobs/8770016011?pr=886#step:6:558

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/5068704275/jobs/9101347076?pr=902#step:6:645

**Comment by patriknw** [comment]
https://github.com/akka/akka-projection/actions/runs/5112202465/jobs/9189980429#step:6:562

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/5476929612/jobs/9975199522#step:6:753

**Comment by pvlugter** [comment]
https://github.com/akka/akka-projection/actions/runs/5791042555/job/15695168847#step:6:665

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/5960389105/job/16167611811#step:6:679

**Comment by pvlugter** [comment]
https://github.com/akka/akka-projection/actions/runs/6230862549/job/16911511387#step:6:680

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/6638344465/job/18034489666#step:6:673
