### ISSUE TITLE
remove docs about `akka-persistence-spanner`

### ISSUE THREAD

**Issue by pjfanning** [akka/akka-projection#774]
I could be wrong but I can't find `akka-persistence-spanner` - it may have been deleted (https://github.com/akka/akka-persistence-spanner/ is 404).

The docs for this repo mention it a few times.

https://doc.akka.io/docs/akka-persistence-spanner/current/ might need to be deleted.

**Comment by johanandren** [comment]
Yes we should remove it from these docs, thanks for the reminder.
