### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by 0bon** [akka/akka-projection#944]
What is the status for scala 3 support for this project ?
It is featured in the main akka guides, and from what I have gathered, is the only project that is still using 2.13 in the guide below: 
https://doc.akka.io/docs/akka-projection/current/getting-started/projection-handler.html

**Comment by octonato** [comment]
Not all artefacts are ready for Scala 3. 

For instance, the Cassandra one has been merged recently and not yet released. See https://github.com/akka/akka-projection/commit/300608cefe45de01ef1c04c19d1adcfcaef46e13

**Comment by octonato** [comment]
@0bon, I just cut the release of v1.5.0-M1 and will show up soon in maven central. 

There are some other works in progress or planned for 1.5.0. There are some new APIs coming in 1.5.0 and that may change between 1.5.0-M1 and the final 1.5.0, but nothing affecting the Cassandra part.  

I believe it's safe for you to start using this milestone release if you restrict yourself to the already existing APIs (APIs that exist in 1.4.x). Try to avoid any new API that has been added in 1.5.0-M1 (you can see all the PRs merged in 1.5.0-M1 here https://github.com/akka/akka-projection/issues?q=is%3Aclosed+milestone%3A1.5.0-M1).

**Comment by 0bon** [comment]
Thanks, I built the JARs yesterday and thus far they work very well - Timing on your part was perfect, thankfully, and keep up the good work, some excellent work here.
