### ISSUE TITLE
Make sure ApiMayChange and InternalApi

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#96]
Before final release we should make sure that ApiMayChange is sprinkled at strategic places (not necessary everywhere), and mentioned in reference docs.

Also, make sure that not more than necessary is public.

**Comment by patriknw** [comment]
I did a scan of this for the 0.3 release. Keeping the ticket as a reminder before 1.0

**Comment by ignasi35** [comment]
After #359 and #366 maybe the only missing step would be a review of the package-private usages (see https://github.com/akka/akka-projection/pull/366#discussion_r458718278)

**Comment by renatocaval** [comment]
Let's keep this one open until we cut 1.0.0.
