### ISSUE TITLE
Ensure that in-flight messages from KafkaSourceProvider are not processed for revoked partitions

### ISSUE THREAD

**Issue by seglo** [akka/akka-projection#98]
Raised by @patriknw in https://github.com/akka/akka-projection/pull/80#discussion_r421510629

> Related thought, but for exactlyOnce. The old projection instance is processing offset 17, but before it has been committed to the database there is a hand-over of that topic-partition to another projection instance, reading offset 16, and processing 17. The old instance saves has successfully processed 17 and saves offset 17. The new instance will also process 17. It's not exactly-once.
>
> Any way we can control the hand-over for such scenario?

Possible solution: https://github.com/akka/akka-projection/pull/80#discussion_r421780677

**Comment by seglo** [comment]
By using Alpakka Kafka's `PartitionAssignmentHandler` we can stay informed about the current subscription of partitions for a consumer group member (a projection instance), but we may not be able to rely on the listener invoking assignment and revoked partition handlers in exceptional circumstances (network partitions).

> It is guaranteed that under normal conditions all the processes in a consumer group will execute their onPartitionsRevoked(Collection) callback before any instance executes its onPartitionsAssigned(Collection) callback. During exceptional scenarios, partitions may be migrated without the old owner being notified (i.e. their onPartitionsRevoked(Collection) callback not triggered), and later when the old owner consumer realized this event, the onPartitionsLost(Collection) (Collection)} callback will be triggered by the consumer then.	

https://kafka.apache.org/25/javadoc/org/apache/kafka/clients/consumer/ConsumerRebalanceListener.html

We can't ensure exactly-once guarantees except by relying on Kafka transactions for both offset storage and the projection target (https://github.com/akka/akka-projection/issues/94), similar to how we can only support exactly-once when the same Slick database is used transactionally for the offset store and the projection.

I think the best we can do for now is find ways to limit the number of possible replays of messages for at least once, and warn people about these issues using Kafka as a source in exactly once.

/cc @patriknw @renatocaval @ennru

**Comment by seglo** [comment]
Should I proceed with a best effort solution?  We can use the `PartitionAssignmentHandler` to manage a set of assigned partitions (with a `ConcurrentHashMap`) and filter messages for non-assigned partitions in the event handler.  We could also check after the event handler and throw an exception to abort the transaction if using exactly-once.

**Comment by patriknw** [comment]
That sounds like a good best effort.

I was also thinking that we could defer the revoke until current element had been completed so that it's not assigned in the new location too early, but I see that `onRevoke` doesn't return a Future so I guess it would be blocking if possible at all. Better to check afterwards and rollback the transaction as you suggest.
